### ISSUE TITLE
Plugin health check failed

### ISSUE THREAD

**Issue by oscardelgadomohatar** [fr-ser/grafana-sqlite-datasource#10]
For some reason, the plugin fails when I click the 'Save & Test' button. I'm sure the path to the DB file is correct, and the file is readable for 'grafana' user. I don't know what is failing exactly, because I cannot find any specific logs. Any idea or suggestions, please! :) :)

**Comment by fr-ser** [comment]
Hey @oscardelgadomohatar .
Thank you for using/trying the plugin even in such early development stages.

But I can't really do much with the information provided above... Could you add your Grafana Version and Operating System maybe?

Also you might want to turn on "DEBUG"-Level logs in Grafana ([see grafana documentation](https://grafana.com/docs/grafana/latest/administration/configuration/#log)).
If you post the output of this (which can be very long in DEBUG mode) I might be able to help more.

**Comment by Ginson** [comment]
> For some reason, the plugin fails when I click the 'Save & Test' button. I'm sure the path to the DB file is correct, and the file is readable for 'grafana' user. I don't know what is failing exactly, because I cannot find any specific logs. Any idea or suggestions, please! :) :)



> For some reason, the plugin fails when I click the 'Save & Test' button. I'm sure the path to the DB file is correct, and the file is readable for 'grafana' user. I don't know what is failing exactly, because I cannot find any specific logs. Any idea or suggestions, please! :) :)

Even i'm getting the same error. 
Grafana ver 7.2.2 on Ubuntu 20.04.1 LTS 64-bit. Due to restrictions I'm unable to upload debug  logs. 
I was waiting for this plugin from 2018. Thanks for publishing

**Comment by fr-ser** [comment]
@Ginson and @oscardelgadomohatar 
I tried the v0.1.1 release and there was indeed a problem with the plugin.
The files were simply not marked as executable (for the Linux users among us `chmod +x ./dist/gpx*`).

I fixed this issue and released v0.1.2 of the plugin with the fix. Could you please try this out

By the way. Even on `info` level the Grafana logs should show you, that the plugin was not installed because of "PermissionError". So if your problem persists, please send me a startup log of your Grafana instance.

**Comment by Ginson** [comment]
> @Ginson and @oscardelgadomohatar
> I tried the v0.1.1 release and there was indeed a problem with the plugin.
> The files were simply not marked as executable (for the Linux users among us `chmod +x ./dist/gpx*`).
> 
> I fixed this issue and released v0.1.2 of the plugin with the fix. Could you please try this out
> 
> By the way. Even on `info` level the Grafana logs should show you, that the plugin was not installed because of "PermissionError". So if your problem persists, please send me a startup log of your Grafana instance.

Hi @fr-ser ,

I tried the latest version v0.1.2. The error still persists.
Given below is the grafana log.
Thanks for the quick response.
`
t=2020-10-28T09:31:12+0100 lvl=info msg="Starting Grafana" logger=server version=7.2.2 commit=ad9d408ac2 branch=HEAD compiled=2020-10-21T09:26:59+0200
t=2020-10-28T09:31:12+0100 lvl=info msg="Config loaded from" logger=settings file=/usr/share/grafana/conf/defaults.ini
t=2020-10-28T09:31:12+0100 lvl=info msg="Config loaded from" logger=settings file=/etc/grafana/grafana.ini
t=2020-10-28T09:31:12+0100 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.data=/var/lib/grafana"
t=2020-10-28T09:31:12+0100 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.logs=/var/log/grafana"
t=2020-10-28T09:31:12+0100 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.plugins=/var/lib/grafana/plugins"
t=2020-10-28T09:31:12+0100 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.provisioning=/etc/grafana/provisioning"
t=2020-10-28T09:31:12+0100 lvl=info msg="Path Home" logger=settings path=/usr/share/grafana
t=2020-10-28T09:31:12+0100 lvl=info msg="Path Data" logger=settings path=/var/lib/grafana
t=2020-10-28T09:31:12+0100 lvl=info msg="Path Logs" logger=settings path=/var/log/grafana
t=2020-10-28T09:31:12+0100 lvl=info msg="Path Plugins" logger=settings path=/var/lib/grafana/plugins
t=2020-10-28T09:31:12+0100 lvl=info msg="Path Provisioning" logger=settings path=/etc/grafana/provisioning
t=2020-10-28T09:31:12+0100 lvl=info msg="App mode production" logger=settings
t=2020-10-28T09:31:12+0100 lvl=info msg="Writing PID file" logger=server path=/var/run/grafana/grafana-server.pid pid=59431
t=2020-10-28T09:31:12+0100 lvl=info msg="Connecting to DB" logger=sqlstore dbtype=sqlite3
t=2020-10-28T09:31:12+0100 lvl=info msg="Starting DB migrations" logger=migrator
t=2020-10-28T09:31:12+0100 lvl=info msg="Starting plugin search" logger=plugins
t=2020-10-28T09:31:12+0100 lvl=info msg="Registering plugin" logger=plugins name=sqlite-datasource
t=2020-10-28T09:31:12+0100 lvl=info msg="Registering plugin" logger=plugins name="Direct Input"
t=2020-10-28T09:31:12+0100 lvl=info msg="Registering plugin" logger=plugins name="Worldmap Panel"
t=2020-10-28T09:31:12+0100 lvl=info msg="HTTP Server Listen" logger=http.server address=[::]:3000 protocol=http subUrl= socket=
t=2020-10-28T09:31:53+0100 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=[::1] time_ms=0 size=29 referer=
t=2020-10-28T09:32:08+0100 lvl=info msg="Successful Login" logger=http.server User=admin@localhost
t=2020-10-28T09:32:31+0100 lvl=eror msg="Plugin health check failed" logger=context userId=1 orgId=1 uname=admin error="Failed to check plugin health: Health check failed" remote_addr=[::1]
t=2020-10-28T09:32:31+0100 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/3/health status=500 remote_addr=[::1] time_ms=3 size=40 referer=http://localhost:3000/datasources/edit/3/
t=2020-10-28T09:33:26+0100 lvl=eror msg="Plugin health check failed" logger=context userId=1 orgId=1 uname=admin error="Failed to check plugin health: Health check failed" remote_addr=[::1]
t=2020-10-28T09:33:26+0100 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/3/health status=500 remote_addr=[::1] time_ms=1 size=40 referer=http://localhost:3000/datasources/edit/3/
t=2020-10-28T09:33:55+0100 lvl=eror msg="Plugin health check failed" logger=context userId=1 orgId=1 uname=admin error="Failed to check plugin health: Health check failed" remote_addr=[::1]
t=2020-10-28T09:33:55+0100 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/3/health status=500 remote_addr=[::1] time_ms=1 size=40 referer=http://localhost:3000/datasources/edit/3/
t=2020-10-28T09:34:00+0100 lvl=eror msg="Plugin health check failed" logger=context userId=1 orgId=1 uname=admin error="Failed to check plugin health: Health check failed" remote_addr=[::1]
t=2020-10-28T09:34:00+0100 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/3/health status=500 remote_addr=[::1] time_ms=1 size=40 referer=http://localhost:3000/datasources/edit/3/
`

**Comment by fr-ser** [comment]
@Ginson That's a lot of text for an issue comment and new lines are missing there.
Maybe uploading a text file somewhere to download might make more sense next time :sweat_smile: 

After looking at your logs I see the following lines in your logs

```txt
t=2020-10-28T09:31:12+0100 lvl=info msg="Starting plugin search" logger=plugins 
t=2020-10-28T09:31:12+0100 lvl=info msg="Registering plugin" logger=plugins name=sqlite-datasource 
t=2020-10-28T09:31:12+0100 lvl=info msg="Registering plugin" logger=plugins name="Direct Input" 
t=2020-10-28T09:31:12+0100 lvl=info msg="Registering plugin" logger=plugins name="Worldmap Panel" 
t=2020-10-28T09:31:12+0100 lvl=info msg="HTTP Server Listen" logger=http.server address=[::]:3000 protocol=http subUrl= socket= 
```

Whereas on my machine it looks like this

```txt
t=2020-10-28T11:44:34+0000 lvl=info msg="Starting plugin search" logger=plugins
t=2020-10-28T11:44:34+0000 lvl=info msg="Registering plugin" logger=plugins name="Direct Input"
t=2020-10-28T11:44:34+0000 lvl=warn msg="Running an unsigned backend plugin" logger=plugins pluginID=frser-sqlite-datasource pluginDir=/var/lib/grafana/plugins/sqlite-datasource/dist
t=2020-10-28T11:44:34+0000 lvl=info msg="Registering plugin" logger=plugins name=sqlite-datasource
t=2020-10-28T11:44:34+0000 lvl=info msg="HTTP Server Listen" logger=http.server address=[::]:3000 protocol=http subUrl= socket=
```

To be precise this line is suspiciously missing from your logs
```txt
t=2020-10-28T11:44:34+0000 lvl=warn msg="Running an unsigned backend plugin" logger=plugins pluginID=frser-sqlite-datasource pluginDir=/var/lib/grafana/plugins/sqlite-datasource/dist
```

Could you have a look at this (new) part of the Readme and check if this is your problem: https://github.com/fr-ser/grafana-sqlite-datasource#allowing-unsigned-plugins

**Comment by Ginson** [comment]
@fr-ser : Thanks for pointing out the unsigned plugins stuff. I have fixed it now. But, still I get the same error. Sorry for copy pasting the log without formatting. Attaching the error log. But now I can see the "suspiciously missing line" which you had mentioned in your previous comment.
[grafana.log](https://github.com/fr-ser/grafana-sqlite-datasource/files/5454918/grafana.log)

**Comment by fr-ser** [comment]
Alright. In that case, I have no further leads.
I heard from other people, that v0.1.2 fixed the issue, so maybe at least @oscardelgadomohatar's problem is gone.

Unless you can give me another lead to check I don't think there is anything I can do @Ginson 
Leads might be:
- debug-level logs
- a reproducible setup (e.g. github repo with docker-compose that shows the plugin not working)

**Comment by oscardelgadomohatar** [comment]
Hi guys!

The first solution provided by @fr-ser worked for me (enabling execution permissions). 

Thanks @fr-ser for your excellent work!! Hopefully this plugin will soon be accepted as official in Grafana, it's really useful.

Regards,

**Comment by Ginson** [comment]
Hi @fr-ser , I tried this plugin in few other machines, it was working fine.

Thanks a lot for creating this plugin!!!

**Comment by fr-ser** [comment]
I am glad the problem got solved

**Comment by ericwb** [comment]
I'm getting this same error.  The debug output doesn't seem to indicate anything useful.

```
t=2021-01-22T16:18:45-0800 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=0
t=2021-01-22T16:18:52-0800 lvl=dbug msg="Received command to update data source" logger=datasources url=
t=2021-01-22T16:18:52-0800 lvl=dbug msg="Querying for data source via SQL store" logger=datasources id=1 orgId=1
t=2021-01-22T16:18:52-0800 lvl=eror msg="Plugin health check failed" logger=context userId=1 orgId=1 uname=admin error="Failed to check plugin health: Health check failed" remote_addr=127.0.0.1
t=2021-01-22T16:18:52-0800 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/1/health status=500 remote_addr=127.0.0.1 time_ms=0 size=40 referer=http://localhost:3000/datasources/edit/1/
t=2021-01-22T16:18:55-0800 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=0
```

**Comment by ericwb** [comment]
Hmm, seems this plugin doesn't support macOS.  Not sure why Grafana allows a user to install an unsupported plugin.  Oh well.

**Comment by fr-ser** [comment]
Yes, macOS is not supported yet. The ticket to follow is here: https://github.com/fr-ser/grafana-sqlite-datasource/issues/7

A workaround would be to use Grafana via Docker

**Comment by yoneoa** [comment]
I'm currently also experiencing the same issue running on Centos7 and Grafana enterprise. The chmod solution unfortunately didn't work either. I was also experiencing the same issue on the OSS version of Grafana on Red Hat. Thanks!

**Comment by fr-ser** [comment]
> I'm currently also experiencing the same issue running on Centos7 and Grafana enterprise. The chmod solution unfortunately didn't work for me. I was also experiencing the same issue on the OSS version of Grafana on Red Hat. Thanks!

To be fair this issue right now (from the title and first message) is simply "it doesn't work".
To make your issue actionable I need some more information like (debug level) logs from Grafana.

**Comment by yoneoa** [comment]
I'm attaching relevant logs, didn't attach before because they're the same as the ones brought up earlier in the thread.
[debug.log](https://github.com/fr-ser/grafana-sqlite-datasource/files/6118305/debug.log)

**Comment by fr-ser** [comment]
> I'm attaching relevant logs, didn't attach before because they're the same as the ones brought up earlier in the thread.
> [debug.log](https://github.com/fr-ser/grafana-sqlite-datasource/files/6118305/debug.log)

Jup, that doesn't really say much. I would need debug level logs to see what Grafana is having problems with.

**Comment by yoneoa** [comment]
Yes, I installed via the cli. I'm going to try directly unzipping the file from github next. 
I'll try to get together debug level logs

**Comment by fr-ser** [comment]
Nothing much should be able to go wrong when installing with the CLI. Maybe it is really an operating system issue. The debug logs might say more...

**Comment by ssnkhan** [comment]
Seeing the same error relating to `Plugin health check failed`:

1. Running Ubuntu LTS
2. Running the latest version of Grafana
3. Installed the plugin via the CLI, then realised it was out of date
4. Uninstalled, then manually installed, now running 1.0.2
5. Set full access on the db via `chmod 777`, and the same with everything under `grafana/plugins/`


```
t=2021-03-25T18:31:41+0000 lvl=info msg="Starting Grafana" logger=server version=7.5.0 commit=b144fb1a9f branch=HEAD compiled=2021-03-25T10:13:32+0000
t=2021-03-25T18:31:41+0000 lvl=info msg="Config loaded from" logger=settings file=/usr/share/grafana/conf/defaults.ini
t=2021-03-25T18:31:41+0000 lvl=info msg="Config loaded from" logger=settings file=/etc/grafana/grafana.ini
t=2021-03-25T18:31:41+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.data=/var/lib/grafana"
t=2021-03-25T18:31:41+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.logs=/var/log/grafana"
t=2021-03-25T18:31:41+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.plugins=/var/lib/grafana/plugins"
t=2021-03-25T18:31:41+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.provisioning=/etc/grafana/provisioning"
t=2021-03-25T18:31:41+0000 lvl=info msg="Path Home" logger=settings path=/usr/share/grafana
t=2021-03-25T18:31:41+0000 lvl=info msg="Path Data" logger=settings path=/var/lib/grafana
t=2021-03-25T18:31:41+0000 lvl=info msg="Path Logs" logger=settings path=/var/log/grafana
t=2021-03-25T18:31:41+0000 lvl=info msg="Path Plugins" logger=settings path=/var/lib/grafana/plugins
t=2021-03-25T18:31:41+0000 lvl=info msg="Path Provisioning" logger=settings path=/etc/grafana/provisioning
t=2021-03-25T18:31:41+0000 lvl=info msg="App mode production" logger=settings
t=2021-03-25T18:31:41+0000 lvl=info msg="Writing PID file" logger=server path=/var/run/grafana/grafana-server.pid pid=698
t=2021-03-25T18:31:41+0000 lvl=info msg="Connecting to DB" logger=sqlstore dbtype=sqlite3
t=2021-03-25T18:31:41+0000 lvl=info msg="Starting DB migrations" logger=migrator
t=2021-03-25T18:31:41+0000 lvl=info msg="migrations completed" logger=migrator performed=0 skipped=279 duration=1.368306ms
t=2021-03-25T18:31:41+0000 lvl=info msg="Starting plugin search" logger=plugins
t=2021-03-25T18:31:41+0000 lvl=info msg="Registering plugin" logger=plugins id=input
t=2021-03-25T18:31:43+0000 lvl=info msg="Registering plugin" logger=plugins id=marcusolsson-treemap-panel
t=2021-03-25T18:31:43+0000 lvl=info msg="Registering plugin" logger=plugins id=frser-sqlite-datasource
t=2021-03-25T18:31:43+0000 lvl=info msg="Registering plugin" logger=plugins id=grafana-worldmap-panel
t=2021-03-25T18:31:43+0000 lvl=info msg="HTTP Server Listen" logger=http.server address=[::]:3000 protocol=http subUrl= socket=
t=2021-03-25T18:34:02+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/login status=302 remote_addr=127.0.0.1 time_ms=5 size=24 referer=
t=2021-03-25T18:34:19+0000 lvl=eror msg="Plugin health check failed" logger=context userId=1 orgId=1 uname=admin error="failed to check plugin health: health check failed" remote_addr=127.0.0.1
t=2021-03-25T18:34:19+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/2/health status=500 remote_addr=127.0.0.1 time_ms=3 size=40 referer=http://127.0.0.1:3000/datasources/edit/2/
t=2021-03-25T18:46:16+0000 lvl=eror msg="Plugin health check failed" logger=context userId=1 orgId=1 uname=admin error="failed to check plugin health: health check failed" remote_addr=127.0.0.1
t=2021-03-25T18:46:16+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/2/health status=500 remote_addr=127.0.0.1 time_ms=1 size=40 referer=http://127.0.0.1:3000/datasources/edit/2/
t=2021-03-25T18:46:17+0000 lvl=eror msg="Plugin health check failed" logger=context userId=1 orgId=1 uname=admin error="failed to check plugin health: health check failed" remote_addr=127.0.0.1
t=2021-03-25T18:46:17+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/2/health status=500 remote_addr=127.0.0.1 time_ms=1 size=40 referer=http://127.0.0.1:3000/datasources/edit/2/
t=2021-03-25T18:46:18+0000 lvl=eror msg="Plugin health check failed" logger=context userId=1 orgId=1 uname=admin error="failed to check plugin health: health check failed" remote_addr=127.0.0.1
t=2021-03-25T18:46:18+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/2/health status=500 remote_addr=127.0.0.1 time_ms=1 size=40 referer=http://127.0.0.1:3000/datasources/edit/2/
t=2021-03-25T18:46:18+0000 lvl=eror msg="Plugin health check failed" logger=context userId=1 orgId=1 uname=admin error="failed to check plugin health: health check failed" remote_addr=127.0.0.1
t=2021-03-25T18:46:18+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/2/health status=500 remote_addr=127.0.0.1 time_ms=1 size=40 referer=http://127.0.0.1:3000/datasources/edit/2/
t=2021-03-25T18:46:18+0000 lvl=eror msg="Plugin health check failed" logger=context userId=1 orgId=1 uname=admin error="failed to check plugin health: health check failed" remote_addr=127.0.0.1
t=2021-03-25T18:46:18+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/2/health status=500 remote_addr=127.0.0.1 time_ms=1 size=40 referer=http://127.0.0.1:3000/datasources/edit/2/
t=2021-03-25T18:46:19+0000 lvl=eror msg="Plugin health check failed" logger=context userId=1 orgId=1 uname=admin error="failed to check plugin health: health check failed" remote_addr=127.0.0.1
t=2021-03-25T18:46:19+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/2/health status=500 remote_addr=127.0.0.1 time_ms=1 size=40 referer=http://127.0.0.1:3000/datasources/edit/2/
t=2021-03-25T18:46:19+0000 lvl=eror msg="Plugin health check failed" logger=context userId=1 orgId=1 uname=admin error="failed to check plugin health: health check failed" remote_addr=127.0.0.1
t=2021-03-25T18:46:19+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/2/health status=500 remote_addr=127.0.0.1 time_ms=1 size=40 referer=http://127.0.0.1:3000/datasources/edit/2/
t=2021-03-25T18:52:42+0000 lvl=info msg="Shutdown started" logger=server reason="System signal: terminated"
```

Really appreciate your help -- I have tried everything else on this thread, and am struggling to get this working.

**Comment by fr-ser** [comment]
Could you post debug level logs?

**Comment by ssnkhan** [comment]
Thank you, is this any better?

```
t=2021-03-25T20:53:35+0000 lvl=dbug msg="Loading plugin" logger=plugins path=/var/lib/grafana/plugins/frser-sqlite-datasource/plugin.json
t=2021-03-25T20:53:35+0000 lvl=dbug msg="Getting signature state of plugin" logger=plugins plugin=frser-sqlite-datasource isBackend=true
t=2021-03-25T20:53:35+0000 lvl=dbug msg="Verifying contents of plugin manifest" logger=plugins plugin=frser-sqlite-datasource
t=2021-03-25T20:53:35+0000 lvl=dbug msg="Plugin signature valid" logger=plugins id=frser-sqlite-datasource
t=2021-03-25T20:53:35+0000 lvl=dbug msg="Loading plugin" logger=plugins path=/var/lib/grafana/plugins/grafana-worldmap-panel/dist/plugin.json
t=2021-03-25T20:53:35+0000 lvl=dbug msg="Getting signature state of plugin" logger=plugins plugin=grafana-worldmap-panel isBackend=false
t=2021-03-25T20:53:35+0000 lvl=dbug msg="Verifying contents of plugin manifest" logger=plugins plugin=grafana-worldmap-panel
t=2021-03-25T20:53:35+0000 lvl=dbug msg="Plugin signature valid" logger=plugins id=grafana-worldmap-panel
t=2021-03-25T20:53:35+0000 lvl=dbug msg="Loading plugin" logger=plugins path=/var/lib/grafana/plugins/marcusolsson-treemap-panel/plugin.json
t=2021-03-25T20:53:35+0000 lvl=dbug msg="Getting signature state of plugin" logger=plugins plugin=marcusolsson-treemap-panel isBackend=false
t=2021-03-25T20:53:35+0000 lvl=dbug msg="Verifying contents of plugin manifest" logger=plugins plugin=marcusolsson-treemap-panel
t=2021-03-25T20:53:35+0000 lvl=dbug msg="Plugin signature valid" logger=plugins id=marcusolsson-treemap-panel
t=2021-03-25T20:53:35+0000 lvl=dbug msg="Initial plugin loading done" logger=plugins
t=2021-03-25T20:53:35+0000 lvl=dbug msg="Found plugin" logger=plugins id=frser-sqlite-datasource signature=valid hasRoot=false
t=2021-03-25T20:53:35+0000 lvl=dbug msg="Plugin has valid signature" logger=plugins id=frser-sqlite-datasource
t=2021-03-25T20:53:35+0000 lvl=dbug msg="Attempting to add plugin" logger=plugins id=frser-sqlite-datasource
t=2021-03-25T20:53:35+0000 lvl=info msg="Registering plugin" logger=plugins id=frser-sqlite-datasource
t=2021-03-25T20:53:35+0000 lvl=dbug msg="Registering backend plugin" logger=plugins.backend pluginId=frser-sqlite-datasource
t=2021-03-25T20:53:35+0000 lvl=dbug msg="Backend plugin registered" logger=plugins.backend pluginId=frser-sqlite-datasource
t=2021-03-25T20:53:35+0000 lvl=dbug msg="Successfully added plugin" logger=plugins id=frser-sqlite-datasource
t=2021-03-25T20:53:35+0000 lvl=dbug msg="Found plugin" logger=plugins id=grafana-worldmap-panel signature=valid hasRoot=false
t=2021-03-25T20:53:35+0000 lvl=dbug msg="Plugin has valid signature" logger=plugins id=grafana-worldmap-panel
t=2021-03-25T20:53:35+0000 lvl=dbug msg="Attempting to add plugin" logger=plugins id=grafana-worldmap-panel
t=2021-03-25T20:53:35+0000 lvl=info msg="Registering plugin" logger=plugins id=grafana-worldmap-panel
t=2021-03-25T20:53:35+0000 lvl=dbug msg="Successfully added plugin" logger=plugins id=grafana-worldmap-panel
t=2021-03-25T20:53:35+0000 lvl=dbug msg="Found plugin" logger=plugins id=marcusolsson-treemap-panel signature=valid hasRoot=false
t=2021-03-25T20:53:35+0000 lvl=dbug msg="Plugin has valid signature" logger=plugins id=marcusolsson-treemap-panel
t=2021-03-25T20:53:35+0000 lvl=dbug msg="Attempting to add plugin" logger=plugins id=marcusolsson-treemap-panel
t=2021-03-25T20:53:35+0000 lvl=info msg="Registering plugin" logger=plugins id=marcusolsson-treemap-panel
t=2021-03-25T20:53:35+0000 lvl=dbug msg="Successfully added plugin" logger=plugins id=marcusolsson-treemap-panel
t=2021-03-25T20:53:35+0000 lvl=dbug msg="GrafanaLive initialization" logger=live
t=2021-03-25T20:53:35+0000 lvl=dbug msg="GrafanaLive feature not enabled, skipping initialization" logger=live
t=2021-03-25T20:53:35+0000 lvl=dbug msg="Registering backend plugin" logger=plugins.backend pluginId=testdata
t=2021-03-25T20:53:35+0000 lvl=dbug msg="Backend plugin registered" logger=plugins.backend pluginId=testdata
t=2021-03-25T20:53:35+0000 lvl=dbug msg=initing logger=tsdb.cloudwatch
t=2021-03-25T20:53:35+0000 lvl=dbug msg="Looking for plugin provisioning files" logger=provisioning.plugins path=/etc/grafana/provisioning/plugins
t=2021-03-25T20:53:35+0000 lvl=dbug msg="Parsing plugin provisioning file" logger=provisioning.plugins path=/etc/grafana/provisioning/plugins file.Name=sample.yaml
t=2021-03-25T20:53:35+0000 lvl=dbug msg="Validating plugins" logger=provisioning.plugins
t=2021-03-25T20:53:35+0000 lvl=dbug msg="Looking for alert notification provisioning files" logger=provisioning.notifiers path=/etc/grafana/provisioning/notifiers
t=2021-03-25T20:53:35+0000 lvl=dbug msg="Parsing alert notifications provisioning file" logger=provisioning.notifiers path=/etc/grafana/provisioning/notifiers file.Name=sample.yaml
t=2021-03-25T20:53:35+0000 lvl=dbug msg="Validating alert notifications" logger=provisioning.notifiers
t=2021-03-25T20:53:35+0000 lvl=dbug msg="NOTIFY_SOCKET environment variable empty or unset, can't send systemd notification" logger=server
t=2021-03-25T20:53:35+0000 lvl=dbug msg="Waiting on services..." logger=server
t=2021-03-25T20:53:35+0000 lvl=dbug msg="No image renderer found/installed. For image rendering support please install the grafana-image-renderer plugin. Read more at https://grafana.com/docs/grafana/latest/administration/image_rendering/" logger=rendering
t=2021-03-25T20:53:35+0000 lvl=dbug msg="Looking for App Dashboard Updates" logger=plugins
t=2021-03-25T20:53:35+0000 lvl=dbug msg="Found old rendered image to delete" logger=cleanup deleted=0 kept=0
t=2021-03-25T20:53:35+0000 lvl=dbug msg="starting plugin" logger=plugins.backend pluginId=frser-sqlite-datasource path=/var/lib/grafana/plugins/frser-sqlite-datasource/gpx_sqlite-datasource_linux_amd64 args=[/var/lib/grafana/plugins/frser-sqlite-datasource/gpx_sqlite-datasource_linux_amd64]
t=2021-03-25T20:53:35+0000 lvl=dbug msg="Plugins: Adding route" logger=http.server route=/public/plugins/marcusolsson-treemap-panel dir=/var/lib/grafana/plugins/marcusolsson-treemap-panel
t=2021-03-25T20:53:35+0000 lvl=dbug msg="Plugins: Adding route" logger=http.server route=/public/plugins/grafana-worldmap-panel dir=/var/lib/grafana/plugins/grafana-worldmap-panel/dist
t=2021-03-25T20:53:35+0000 lvl=dbug msg="Plugins: Adding route" logger=http.server route=/public/plugins/input dir=/usr/share/grafana/plugins-bundled/internal/input-datasource
t=2021-03-25T20:53:35+0000 lvl=dbug msg="Plugins: Adding route" logger=http.server route=/public/plugins/frser-sqlite-datasource dir=/var/lib/grafana/plugins/frser-sqlite-datasource
t=2021-03-25T20:53:35+0000 lvl=info msg="HTTP Server Listen" logger=http.server address=[::]:3000 protocol=http subUrl= socket=
t=2021-03-25T20:53:35+0000 lvl=dbug msg="Checking for updates" logger=plugins
t=2021-03-25T20:53:36+0000 lvl=dbug msg="plugin started" logger=plugins.backend pluginId=frser-sqlite-datasource path=/var/lib/grafana/plugins/frser-sqlite-datasource/gpx_sqlite-datasource_linux_amd64 pid=3444
t=2021-03-25T20:53:36+0000 lvl=dbug msg="waiting for RPC address" logger=plugins.backend pluginId=frser-sqlite-datasource path=/var/lib/grafana/plugins/frser-sqlite-datasource/gpx_sqlite-datasource_linux_amd64
t=2021-03-25T20:53:36+0000 lvl=dbug msg="Serving plugin" logger=plugins.backend pluginId=frser-sqlite-datasource plugins="[diagnostics data]"
t=2021-03-25T20:53:36+0000 lvl=dbug msg="plugin address" logger=plugins.backend pluginId=frser-sqlite-datasource address=/tmp/plugin786837280 network=unix
t=2021-03-25T20:53:36+0000 lvl=dbug msg="using plugin" logger=plugins.backend pluginId=frser-sqlite-datasource version=2
t=2021-03-25T20:53:37+0000 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=0
t=2021-03-25T20:53:46+0000 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=0
t=2021-03-25T20:53:56+0000 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=0
t=2021-03-25T20:54:06+0000 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=0
t=2021-03-25T20:54:16+0000 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=0
t=2021-03-25T20:54:26+0000 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=0
t=2021-03-25T20:54:36+0000 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=0
t=2021-03-25T20:54:46+0000 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=0
t=2021-03-25T20:54:56+0000 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=0
t=2021-03-25T20:55:06+0000 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=0
t=2021-03-25T20:55:16+0000 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=0
t=2021-03-25T20:55:26+0000 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=0
t=2021-03-25T20:55:36+0000 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=0
t=2021-03-25T20:55:40+0000 lvl=dbug msg="Updating last user_seen_at" logger=context userId=1 orgId=1 uname=admin user_id=1
t=2021-03-25T20:55:40+0000 lvl=dbug msg="Received command to update data source" logger=datasources url=
t=2021-03-25T20:55:40+0000 lvl=dbug msg="Updating last user_seen_at" logger=context userId=1 orgId=1 uname=admin user_id=1
t=2021-03-25T20:55:40+0000 lvl=dbug msg="Updating last user_seen_at" logger=context userId=1 orgId=1 uname=admin user_id=1
t=2021-03-25T20:55:40+0000 lvl=dbug msg="Updating last user_seen_at" logger=context userId=1 orgId=1 uname=admin user_id=1
t=2021-03-25T20:55:40+0000 lvl=dbug msg="Querying for data source via SQL store" logger=datasources id=6 orgId=1
t=2021-03-25T20:55:40+0000 lvl=eror msg="Plugin health check failed" logger=context userId=1 orgId=1 uname=admin error="failed to check plugin health: health check failed" remote_addr=127.0.0.1
t=2021-03-25T20:55:40+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/6/health status=500 remote_addr=127.0.0.1 time_ms=3 size=40 referer=http://127.0.0.1:3000/datasources/edit/6/
t=2021-03-25T20:55:41+0000 lvl=dbug msg="Updating last user_seen_at" logger=context userId=1 orgId=1 uname=admin user_id=1
t=2021-03-25T20:55:41+0000 lvl=dbug msg="Received command to update data source" logger=datasources url=
t=2021-03-25T20:55:41+0000 lvl=dbug msg="Updating last user_seen_at" logger=context userId=1 orgId=1 uname=admin user_id=1
t=2021-03-25T20:55:41+0000 lvl=dbug msg="Updating last user_seen_at" logger=context userId=1 orgId=1 uname=admin user_id=1
t=2021-03-25T20:55:41+0000 lvl=dbug msg="Updating last user_seen_at" logger=context userId=1 orgId=1 uname=admin user_id=1
t=2021-03-25T20:55:41+0000 lvl=dbug msg="Querying for data source via SQL store" logger=datasources id=6 orgId=1
t=2021-03-25T20:55:41+0000 lvl=eror msg="Plugin health check failed" logger=context userId=1 orgId=1 uname=admin error="failed to check plugin health: health check failed" remote_addr=127.0.0.1
t=2021-03-25T20:55:41+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/6/health status=500 remote_addr=127.0.0.1 time_ms=1 size=40 referer=http://127.0.0.1:3000/datasources/edit/6/
t=2021-03-25T20:55:46+0000 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=0
```

**Comment by ssnkhan** [comment]
I am also seeing a sprinkling of `t=2021-03-25T21:11:29+0000 lvl=eror msg="Could execute query" logger=plugins.backend pluginId=frser-sqlite-datasource err="unable to open database file: permission denied"` - but the database has been chmod'd to 700, so not sure what the issue is.

**Comment by ssnkhan** [comment]
Resolved -- running `sudo chmod -R a+rwX` on the directory fixed it :)

**Comment by fr-ser** [comment]
> I am also seeing a sprinkling of t=2021-03-25T21:11:29+0000 lvl=eror msg="Could execute query" logger=plugins.backend pluginId=frser-sqlite-datasource err="unable to open database file: permission denied" - but the database has been chmod'd to 700, so not sure what the issue is.

Where did you see those logs? Your output does now show it. And `700` does not mean every user can read the database.

> Resolved -- running sudo chmod -R a+rwX on the directory fixed it :)

Glad to hear that. I will have a look in the plugin where error messages are shown for missing permissions and if they can be more prominent.
